# In-Game Account Switcher is a third-party mod for Minecraft Java Edition that
# allows you to change your logged in account in-game, without restarting it.
#
# Copyright (C) 2015-2022 The_Fireplace
# Copyright (C) 2021-2025 VidTu
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues"
clientSideOnly = true

[[mods]]
modId = "ias"
version = "${version}"
displayName = "In-Game Account Switcher"
updateJSONURL = "https://raw.githubusercontent.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/main/updater-neoforge.json"
displayURL = "https://modrinth.com/mod/in-game-account-switcher"
issueTrackerURL = "https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues"
catalogueImageIcon = "ias_64.png"
catalogueItemIcon = "minecraft:player_head"
itemIcon = "minecraft:player_head"
logoFile = "ias_240.png"
credits = "The_Fireplace, The_BrainStone, 2xsaiko, Elvm"
authors = "VidTu"
displayTest = "IGNORE_ALL_VERSION"
description = '''Allows you to change which account you are signed in to in-game without restarting Minecraft.'''

[[mixins]]
config = "ias.mixins.json"

[[dependencies.ias]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "[${minecraft}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ias]]
modId = "${platform}"
type = "required"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[modproperties.ias]
catalogueImageIcon = "ias_64.png"
catalogueItemIcon = "minecraft:player_head"
itemIcon = "minecraft:player_head"
logoFile = "ias_240.png"
