modLoader = "javafml"
loaderVersion = "[0,)"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues"
clientSideOnly = true

[[mods]]
modId = "ias"
version = "${version}"
displayName = "In-Game Account Switcher"
updateJSONURL = "https://raw.githubusercontent.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/main/updater-forge.json"
displayURL = "https://modrinth.com/mod/in-game-account-switcher"
logoFile = "ias.png"
credits = "The_Fireplace, The_BrainStone, 2xsaiko, Elvm"
authors = "VidTu"
displayTest = "IGNORE_ALL_VERSION"
description = '''
Allows you to change which account you are signed in to in-game without restarting Minecraft.
'''

[[dependencies.ias]]
modId = "forge"
type = "required"
mandatory = true
versionRange = "[45,46)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ias]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "1.19.4"
ordering = "NONE"
side = "CLIENT"
